version: '3.0'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: goodjob
      MYSQL_USER: user
      MYSQL_PASSWORD: p4ssw0rd
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume: