version: '3.0'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
    ports:
      - $DATABASE_COMPUTER_PORT:$DATABASE_CONTAINER_PORT
    volumes:
      - data-volume:$DATABASE_MIGRATION_PATH
volumes:
  data-volume: